### ISSUE TITLE
Can't activate plug-in

### ISSUE THREAD

**Issue by gstout** [Hube2/acf-post2post#17]
This beautiful little plugin is exactly the bidirectionally relationship solution I've been seeking. 

I'm on a multisite network and can't get the plug-in to activate. When i click activate on **one** of the multisite plugin screen, I get an "Plugin activated." message  but the plug-in listing doesn't change state. It still says "Activate" and it's functionality doesn't seem to be working. 

Same happens if I try to network activate it.

**Comment by Hube2** [comment]
What version of ACF are you using. This plugin will only work with ACF5 and can't be activated if you're using ACF4.

**Comment by kLOsk** [comment]
Hi, I'm actually seeing the same issue. Running latest ACF Pro 5.6.10 - Any idea how to debug?

**Comment by kLOsk** [comment]
oh, actually I just realized that I have embedded ACF into the theme instead of installed as a plugin. Will see if i can fix it.

**Comment by kLOsk** [comment]
Sorry for spamming, so the reason why it fails is because the plugin checks for ACF on the hook 'plugins_loaded'. Replacing this with 'after_setup_theme' solves the problem.
Since embedding ACF into themes is officially supported, I would recommend to adjust this. Since it's just one line of code I hope you don't mind me not creating a pull request for this.

Line 27 acf-post2post.php:
`add_action('after_setup_theme', array($this, 'plugins_loaded'));`

**Comment by Hube2** [comment]
I altered to run on after_setup_theme. I'd like to remove this completely. Hopefully ACF5 will be released to WP soon and I can do so eventually.
