### ISSUE TITLE
Order of Posts Not Preserved

### ISSUE THREAD

**Issue by chumpgrub** [Hube2/acf-post2post#21]
Hi John, my client is experiencing an issue which I'm having difficulty finding a solution to.

We have a custom post type that can be joined via the relationship field to pages. Typically pages will have several of the CPT joined to them, and the CPT are sequenced within the relationship field on the page. I'm experiencing intermittent issues, where, when the act of saving the CPT (previously associated with a page) will cause the sequence on the joined page to change. The CPT that's been saved, will be moved from wherever it had originally been to the end.

The relationship fields are not nested and I have no quantity limits imposed. Do you have any recommendations for debugging this scenario?

Thank you for your time, and thank you for the great plugin.

**Comment by Hube2** [comment]
I just did a test and I can't reproduce this. I would need more information on the steps to recreate the issue.

There is only one thing that I can think of and that would be removing and then re-adding the relationship.

For example: 
If on the CPT you have the relationships
- Page 1
- Page 2
- Page 3
And lets say that on Page 1 there are the relationships
- CPT 1
- CPT 2
- CPT 3
and you edited the CPT 1 and removed "Page 1" and saved and then you re-add "Page 1" and save again. Then CPT 1 will more to the bottom of the list on Page 1. This is because it is a new relationship and it is automatically added to the end of the list when adjusting the other end.

Hopefully that makes sense to you and I've explained it well enough. In the end, the only way for the order to change on the other end is to remove and an then re-add something.

**Comment by chumpgrub** [comment]
Hi John,

I have more information regarding the issue we're experiencing and it seems to involve Wordpress revisions.

## Steps to reproduce:
1. Create new page and add CPT relationships and allow post to auto-save.
-- This will add a `post` record with a `post_status` of `draft`.

2. Order the CPT in the ACF Relationship Field.

3. Click “preview” to view draft page.
-- The act of previewing the page creates another post record, but with the `post_status` of `inherit`.

4. Observe the `postmeta` relationship field for one of the CPT's in your page's relationship field. 
-- You should see the `post` ID of the latest (inherit) version of the Page.

5. Publish the draft Page and revisit the `postmeta` data from step 3.
-- The relationship field will now include both the published `post` ID and the previous, inherited, `post` ID.

6. Open CPT from page’s relationship field and save.
-- Act of saving will remove the inherited `post` ID from CPT `postmeta` relationship field.
-- The removal of inherited `post` ID will cause re-ordering of CPT arrangement made in step 2.

Thanks again, for your time and guidance on the matter!

**Comment by Hube2** [comment]
As I said in my last comment, the post IDs are being altered. In this case when you publish the page the ID is not the same as the ID when it is a draft and being previewed. The only thing that I have to go by here is the post IDs that ACF is saving. The main issue is really that a post is being added to a relationship field before it is published, and I was not aware that ACF would even show unpublished pages in a relationship field.

I'm not even sure I understand this behavior or why it is happening. When I test this

1) I start a new post of post type A and I let it autosave.
2) Then I monitor the relationship field on the other side on the relationship in post type B - I see the new draft post that I can select - in this test the post ID for it is 26
3) I then preview the post that was autosave, the post ID is still 26
4) I then publish the post that I just previewed, the post ID is still 26

However, If I do this
1) Create a new post in post type A
2) G0 to a post of post type B and add the aurtosave post to the relationship field
3) Preview this page, (remember we have not actually altered the relationship field of post type A yet. What this means is that we are saving an empty relationship. This causes the relationship on post type B to be removed.
4) Now if we select the post in post type B in the relationship field on post type A and save post type A, the relationship will then be added to the end of the list for post type B because it was removed in step 3

I think the main issue here is that both ends of the relationship are being edited at the same time and the lack of the relationship on either end when a post is saved will cause the other end to be updated to remove that relationship. What really matters is what is in a relationship for a post when it is saved.

**Comment by chumpgrub** [comment]
I was hoping this could be an opportunity to leverage the update filter in method `update_relationship_field()` in `acf-post2post.php`. I thought perhaps I could pass back `false` to prevent the update if I could detect whether or not the event triggering it was an auto-save or revision, but I'm making no headway.

```
add_filter( 'acf/post2post/update_relationships/key=field_53c982bbe7eab', function ( $update ) {
	// Check to see if we are autosaving
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
		return FALSE;
	}

	return $update;
} );
```

I'm attempting to prevent update to the relationship field, if autosaving, but I don't believe the timing is right for a meaningful check.

Do you have any recommendations for where I might implement this type of check? Or, do you have an alternative idea for managing this situation?

**Comment by Hube2** [comment]
ACF fields should not be being saved during an autosave. There have been many topics started on the ACF forum on this subject because WP does not send custom fields (acf fields) during the autosave, so there is not trigger for ACF to update any fields. I suspect that this is happening when clicking on previewing the post when the post is actually saved as a draft.

I can look at additional parameters for that filter, for example it is currently only meant to completely disable the updating of a field completely for a specific field key.  I could also send the post ID of the post being updated. With this a check could be done of the post status. My thinking here is that working simultaneously on both ends of the relationship is not something that most people would do, since this is the first time it's come up and I think it's the root cause of the issue you're seeing.

**Comment by Hube2** [comment]
If your are comfortable doing so to test you could change edit the file on your installation and change this line https://github.com/Hube2/acf-post2post/blob/master/acf-post2post.php#L62 to
```
$update = apply_filters('acf/post2post/update_relationships/key='.$field['key'], $update, $post_id);
```
and then change your filter to check the status of the post being updated. 

But I'm still not sure this will fix your issue depending on the order in which two posts are being updated and same time are updated. You have 2 posts open at the same time and you're making different changes to both posts. Saving on either site will cause an update on the other site that will not be reflected in the open editor unless the page is reloaded. This would require that the other open editor is constantly using AJAX to check the db to see if any changes have been made and then showing those changes automatically.

**Comment by cecilehabran** [comment]
Hi ! 
I have a related issue on my side that might be related : as you mentioned @Hube2 "this is happening when clicking on previewing the post when the post is actually saved as a draft".
When a user is creating a post that has a relationship field, and saves the draft or sees the preview, it updates the related post and add a draft permalink or an autosave one. It's an issue for me, as I now have some posts listing wrong related permalinks (that go to 404 pages).

I tried changing the line you mentioned in the plugin, and then add this filter in my theme : 
```php
function avoidAutoSave($update, $post_id) {
	if (get_post_status( $post_id ) != 'publish') {
                // don't update if post isn't publish
		return false;
	}
	return $update;
}
add_filter( 'acf/post2post/update_relationships/key=field_5d53fcc7139ab', 'avoidAutoSave', 2);
```

But I got an error about the number of arguments. Do I miss something ?
