### ISSUE TITLE
Multiple bi-directional relationships

### ISSUE THREAD

**Issue by davshoward** [Hube2/acf-post2post#23]
Is it possible to have multiple bi-directional relationships?

E.g.

CPT1 <---> CPT2
CPT1 <---> CPT3
CPT2 <---> CPT3

CPT4 <---> CPT5

Would each pairing need its own ACF field group? E.g. 
connected_items_1_2
connected_items_1_3
connected_items_2_3
connected_items_4_5

which would result in 10 groups (one for each direction)

Or is it possible to just have:

connected_items_1
connected_items_2
connected_items_3
connected_items_4
connected_items_5

?

Thanks in advance :-)

**Comment by Hube2** [comment]
You can put the fields in any groups that you want, the only requirement is that the names are the same, and they do not overlap. While you can create a different field group for each relationship and include that field group on the posts you want to relate you can also create a single field group with all of the relationships for that post type. I'm not going to give you a breakdown with 5 Post Types, but I will give an example from one of my sites.

Lets say that we have "Posts", "Pages" and "Products" and we want to relate
```
Posts => Posts
Pages => Posts
Products => Posts
```
On the "Post" post type I would create a field group that includes 3 relationship fields and I would probably name them as follows so that I know what is being related by the field name
```
Field 1 Name = posts_to_posts
Field 2 Name = posts_to_pages
Field 3 Name = posts_to_products
```
In addition to the above I would probably add several other fields that are specific to posts

Then I would create a completely different group for the "page" post type
```
Feild 1 Name = posts_to_pages
```
Again, I might have additional fields in this group used only on pages

I would do the same for the products post type
```
Feild 1 Name = posts_to_products
```
A relationship field does not need to be the same field or in the same field group, it simply needs to have the same name.

**Comment by davshoward** [comment]
Great response - thank you. Implemented as you suggested and all is working 😃👍
