### ISSUE TITLE
post2post 1.3.2 stopped working

### ISSUE THREAD

**Issue by marcosalatin** [Hube2/acf-post2post#27]
Hi,

For some reason two days ago after I made available updates post2post stopped working. It isn't writing values bidirectional as It should, it's just reading what was saved till now in ACF.

Current WP version 4.9.9
No Gutenberg plugin
ACF Post-2-Post 1.3.2
Advanced Custom Fields PRO 5.7.11

Could you verify the situation, please? Otherwise what can I do to repair the issue? It's on a production site that is using post2post as a core function during uploading content, so It's a quite big issue for us.

Thank you very much

**Comment by Hube2** [comment]
There were some bug reported over on ACF forums that have been corrected. In order to get the newest updates Elliot says:

An easy way to re-update is to edit ghe main acf.php plugin file and change the version number from 5.7.11 to 5.7.10

- Please note the version number appears twice in this file and both will need to be changed
- After this changes is made, update the plugin as per normal and it will update to 5.7.11 again (including all fixes)

Can you please try this and see if this corrects your problem.

**Comment by marcosalatin** [comment]
Thank you for a fast reply. 

It resolved the issue.

Question apart. Is there a way to detect an issue like this? To prevent that we publish content when bidirectional connection isn't working.

**Comment by Hube2** [comment]
I don't know of any way to detect issues like this except to make changes and see if they work.
