### ISSUE TITLE
+ Signs in Title

### ISSUE THREAD

**Issue by saschapi** [Hube2/acf-post2post#28]
Hi, I import 2 Post types via WP-All import. Both have a field, that syncs with acf post2post. Problem is: 
There is a custom post with title "MTV+ HD". When imported it syncs with the also present title "MTV HD" instead of "MTV+ HD". Same happens for "Sport1+ HD"
When I add the connection in the relationship field manually it works fine.
Could this be because of the seriailzation functions? I guess the + sign is stripped out. 

Example of the RAW import of the relationship field:
13th Street HD|A&E|Animal Planet HD|auto motor und sport channel|AXN HD|BonGusto|Discovery Channel HD|E! Entertainment|Eurosport 2|Fix&Foxi|FOX HD|Fuel TV HD|Gute Laune TV|Heimatkanal|HISTORY|KinoweltTV|Marco Polo TV|Mezzo Live HD|MTV LIVE HD|NATIONAL GEOGRAPHIC HD|Nick Jr.|Penthouse HD|ProSieben FUN HD|Romance TV|Silverline TV|SONY CHANNEL HD|SPIEGEL TV Wissen HD|sportdigital HD|SYFY HD|wetter.com TV|Playboy TV|ducktv|SPORT1+ HD 

Any idea how to fix this?

Thanks Sascha

**Comment by Hube2** [comment]
There is nothing in this plugin that will effect/automatically create/update relationship fields when using WP All Import. 

I don't know how relationship fields are handled by WPAI. More than likely, since it is titles that are being imported that plugin is attempting to find a post with that title and or name and finding the wrong one. It's probably looking at the "Post Name". 

"MTV+ HD" would be converted to "mtv-hd" for the post name and "MTV HD" would also be converted to "mtv-hd" for the post name. Depending on what order they are imported, one of these would actually end up being "mtv-hd-2" because WP does not allow duplicate post names. Then when WPAI looks for the post to relate it converts "MTV+ HD" to "mtv-hd" and looks for a post matching this post name and finds the wrong one because it's missing the "-2" from the second one that was imported. This is all just guess work, you'd need to talk to the people over at WPAI.

**Comment by saschapi** [comment]
You are right. I checked what happens with WP All Import/Export. Issue was that it was only exporting the titles of the relations as a string. When Importing it somehow made slugs out of the titles and that was relating to issue you guessed. ;) Solution for me was to export slugs instead of titles for the relationship fields. 

Just to let you know: As the posts are updated or newly created, your plugin seems to handle them as if there was a manual update. So it works perfectly. 

Thanks for pointing me in the right direction!
