### ISSUE TITLE
Bi-directional relationship for all selected posts?

### ISSUE THREAD

**Issue by jadlimcaco** [Hube2/acf-post2post#32]
Would something like this be possible?

https://support.advancedcustomfields.com/forums/topic/bidirectional-relationship-for-selected-posts/

---

**Example with the current function:**
Current Post: Post 1
Related Posts: Post 2, Post 3, Post 4, Post 5

Post 2
Related Posts: Post 1

…
Post 5
Related Posts: Post 1

**Example with what I’d like it to do:**
Current Post: Post 1
Related Posts: Post 2, Post 3, Post 4, Post 5

Post 2
Related Posts: Post 1, Post 3, Post 4, Post 5

…
Post 5
Related Posts: Post 1, Post 2, Post 3, Post 4

**Comment by Hube2** [comment]
Not with this plugin and it's not something that I'm likely to try and add. I will look into the possibility of adding some type of hooks so that this could be added by those that are looking to do so. My suggestion right now would be to look at the documentation on ACF and create you're own filters that will do this for a specific field.

**Comment by jadlimcaco** [comment]
Thanks for the quick response. It's pretty surprising that this hasn't been done already, as I think for related posts, this makes sense. I've seen a few people already mention it in the ACF support.

Appreciate all the good quality plugins/resources that you offer. Thanks again.

**Comment by Hube2** [comment]
This plugin does thing automatically. While what you suggest may be wanted in some cases, it will not be wanted in all cases. Since there are no settings there wouldn't be a way to turn it off. And I've already tried doing this and there is a problem with recursion and creating an infinite loop during the update process that is not easy to work around.
