### ISSUE TITLE
Super Helpful - Note on Documentation

### ISSUE THREAD

**Issue by misfist** [Hube2/acf-post2post#6]
Thanks for creating this. It's super helpful!

One suggestion on the documentation... You might mention that the plugin, once activated, uses the existing `Relationship` field to be bi-directional. Happily, it does _not_ create a new field like a lot of other ACF plugins do.

**Comment by Hube2** [comment]
You will need to either update manually or manually one more time edit your copy of the plugin header to add
`
GitHub Plugin URI: https://github.com/Hube2/acf-post2post
`

**Comment by Hube2** [comment]
The above commit note was wrong, I used the wrong issue number. I don't know how to remove it.

**Comment by Hube2** [comment]
I don't know if the addition will help others understand or not. I usually prefer not to add more to the admin when I can and I like using what ACF already provides most of the the time rather than building something else that I need to maintain. 

This plugin is a rather mindless way to achieve the goal as long as you follow the simple rules for the fields it can be used on. My actual goal when creating it was to remove the need of doing the complicated reverse relationship queries needed with the standard fields. 

I can also understand why it is not built into ACF. If this was in ACF then Elliot would need to contend with relationship fields in repeaters and flexible content fields and would also need to deal with relationship fields that use different names and types on other post types. All of the complexities that I can ignore by limiting the scope of where it can be used what needs to be done.

**Comment by misfist** [comment]
Sorry I wasn't clear. I just meant adding some more details to the [GitHub documentation](https://github.com/Hube2/acf-post2post#post-2-post-for-acf). It looks like you already did. Thanks!!
